server:
  port: 30000
spring:
  cloud:
    alicloud:
      oss:
        endpoint: 
        bucket: lanan-gulimall
      access-key: 
      secret-key: 
    nacos:
      discovery:
        group: dev
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
