server:
  port: 30000
spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: lanan-gulimall
      access-key: LTAI5t7oG3Z9UZJMDZ5jSWth
      secret-key: 815pOvF3qRykW5vdzN4fIBZ7CGv3gy
    nacos:
      discovery:
        group: dev
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
